name: Makefile CI        

on:
  workflow_run:
    branches: [ main ]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: make
      run: make test  
