name: Makefile CI        

on:
  workflow_dispatch:
    inputs:
      version:
        type: text
        description: Tag Version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: first fetch
        run: |
          git fetch --force
          git fetch --tags --force
      
      - name: check tags
        run: |
          git fetch --unshallow --tags
          echo $?
          git tag --list
