name: Makefile CI        

on:
  workflow_dispatch:
    inputs:
      version:
        type: text
        description: Tag Version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: first fetch
        id: tag
        run: |
          git fetch --force
          git fetch --tags --force
          echo "VERSION=$(git tag --sort=committerdate | tail -1)" >> $GITHUB_ENV
          echo ${{ env.VERSION }}
