name: Makefile CI        

on:
  workflow_dispatch:
    inputs:
      version:
        type: text
        description: Tag Version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      run: |
        git fetch --unshallow --tags
        echo $?
        git tag --list